### ISSUE TITLE
Each step removes all dead agents from grid

### ISSUE THREAD

**Issue by zmuda** [maciek123/pyage#4] opened 2015-06-09 10:48 UTC
When making step by agent, removing all dead agents is invoked [(line)](https://github.com/maciek123/pyage/blob/master/pyage/core/locator.py#L73).

I'm not sure if traversing the whole grid [(here)](https://github.com/maciek123/pyage/blob/master/pyage/core/locator.py#L93-96) is needed, maybe checking only possible neighborhood would suffice. That would reduce step complexity a great deal. Change should be simple as possible neighborhood is already calculated in scope [(here)](https://github.com/maciek123/pyage/blob/master/pyage/core/locator.py#L75).

I didn't save the config, but it is possible for remove_dead to take more than half of execution time. 

|   ncalls | cumtime |  filename:lineno(function) |
|----------|---------|---------|---------------------------|
|        1 |  **50.313** |  bootstrap.py:16(main)
|   321187  |  41.125  |  locator.py:71(get_neighbour)
|   310858  |  40.664  |  emas.py:19(step)
|   321187  |  **32.305**  |  locator.py:92(_remove_dead)

**Comment by maciek123** [comment] 2015-06-14 21:43
duplicate of #3

**Closed** 2015-06-14 21:42 UTC
